name: Unix distribution

on:
  workflow_dispatch:
  
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up ExifTool
      run: ./dist_unix.sh exiftool

    - name: Package ExifTool
      run: |
        tar cv exiftool | gzip --best > exiftool_unix.tgz
        
    - name: Upload artifact
      uses: actions/upload-artifact@v3

      with:
        name: exiftool_unix.tgz
        path: exiftool_unix.tgz
